version: '3'

services:
  piwigo-photos:
    image: deweiliu/piwigo-photos:latest
    build:
      context: ./src
      dockerfile: Dockerfile
      x-bake:
        platforms:
          - linux/amd64
          - linux/arm64
    container_name: piwigo-container
    ports:
      - 80:80